# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: Messages/Channel.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='Messages/Channel.proto',
  package='',
  serialized_pb=_b('\n\x16Messages/Channel.proto\"e\n\x0f\x43lassStartParam\x12\x0f\n\x07webstie\x18\x01 \x01(\t\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\x10\n\x08password\x18\x03 \x01(\t\x12\x0f\n\x07\x63lassid\x18\x04 \x01(\t\x12\x10\n\x08uniqueid\x18\x05 \x01(\t\",\n\x10\x43lassResultParam\x12\x0c\n\x04port\x18\x01 \x01(\x05\x12\n\n\x02ip\x18\x02 \x01(\t\"c\n\x07\x43hannel\x12&\n\nstartParam\x18\x01 \x01(\x0b\x32\x10.ClassStartParamH\x00\x12(\n\x0bresultParam\x18\x02 \x01(\x0b\x32\x11.ClassResultParamH\x00\x42\x06\n\x04\x62ody')
)
_sym_db.RegisterFileDescriptor(DESCRIPTOR)




_CLASSSTARTPARAM = _descriptor.Descriptor(
  name='ClassStartParam',
  full_name='ClassStartParam',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='webstie', full_name='ClassStartParam.webstie', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='name', full_name='ClassStartParam.name', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='password', full_name='ClassStartParam.password', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='classid', full_name='ClassStartParam.classid', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='uniqueid', full_name='ClassStartParam.uniqueid', index=4,
      number=5, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=26,
  serialized_end=127,
)


_CLASSRESULTPARAM = _descriptor.Descriptor(
  name='ClassResultParam',
  full_name='ClassResultParam',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='port', full_name='ClassResultParam.port', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='ip', full_name='ClassResultParam.ip', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=129,
  serialized_end=173,
)


_CHANNEL = _descriptor.Descriptor(
  name='Channel',
  full_name='Channel',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='startParam', full_name='Channel.startParam', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='resultParam', full_name='Channel.resultParam', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
    _descriptor.OneofDescriptor(
      name='body', full_name='Channel.body',
      index=0, containing_type=None, fields=[]),
  ],
  serialized_start=175,
  serialized_end=274,
)

_CHANNEL.fields_by_name['startParam'].message_type = _CLASSSTARTPARAM
_CHANNEL.fields_by_name['resultParam'].message_type = _CLASSRESULTPARAM
_CHANNEL.oneofs_by_name['body'].fields.append(
  _CHANNEL.fields_by_name['startParam'])
_CHANNEL.fields_by_name['startParam'].containing_oneof = _CHANNEL.oneofs_by_name['body']
_CHANNEL.oneofs_by_name['body'].fields.append(
  _CHANNEL.fields_by_name['resultParam'])
_CHANNEL.fields_by_name['resultParam'].containing_oneof = _CHANNEL.oneofs_by_name['body']
DESCRIPTOR.message_types_by_name['ClassStartParam'] = _CLASSSTARTPARAM
DESCRIPTOR.message_types_by_name['ClassResultParam'] = _CLASSRESULTPARAM
DESCRIPTOR.message_types_by_name['Channel'] = _CHANNEL

ClassStartParam = _reflection.GeneratedProtocolMessageType('ClassStartParam', (_message.Message,), dict(
  DESCRIPTOR = _CLASSSTARTPARAM,
  __module__ = 'Messages.Channel_pb2'
  # @@protoc_insertion_point(class_scope:ClassStartParam)
  ))
_sym_db.RegisterMessage(ClassStartParam)

ClassResultParam = _reflection.GeneratedProtocolMessageType('ClassResultParam', (_message.Message,), dict(
  DESCRIPTOR = _CLASSRESULTPARAM,
  __module__ = 'Messages.Channel_pb2'
  # @@protoc_insertion_point(class_scope:ClassResultParam)
  ))
_sym_db.RegisterMessage(ClassResultParam)

Channel = _reflection.GeneratedProtocolMessageType('Channel', (_message.Message,), dict(
  DESCRIPTOR = _CHANNEL,
  __module__ = 'Messages.Channel_pb2'
  # @@protoc_insertion_point(class_scope:Channel)
  ))
_sym_db.RegisterMessage(Channel)


# @@protoc_insertion_point(module_scope)
